// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"atmail/internal/http"
	"atmail/internal/http/handler"
	"atmail/internal/http/route"
	"atmail/internal/repository"
	"atmail/internal/service"
)

// Injectors from wire.go:

func Initialize() *http.ServerHTTP {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	userRoute := route.NewUserRoute(userHandler)
	serverHTTP := http.NewServerHTTP(userRoute)
	return serverHTTP
}
